export const EMOJI = {
    SUCCESS: '✅',
    ERROR: '❌',
    CANCEL: '❌',
    BACK: '←',
    SEARCH: '🔍',
    MONEY: '💵',
    LIGHTNING: '⚡️',
    SETTINGS: '⚙️',
    ROCKET: '🚀',
    CHART: '📊',
    CHART_UP: '📈',
    CHART_DOWN: '📉',
    GREEN_CIRCLE: '🟢',
    RED_CIRCLE: '🔴',
    DIAMOND: '🔸',
    CLIPBOARD: '📋',
    BULB: '💡',
    WARNING: '⚠️',
} as const;
